FROM python:3.7

WORKDIR /usr/src/app
RUN git clone https://github.com/JacobReynolds/pgsync
WORKDIR pgsync
RUN git checkout redis_batch_write
RUN python3 setup.py develop

# Uncomment if using plugins
# RUN mkdir /usr/src/pythonpath/
# COPY ./plugins /usr/src/pythonpath/plugins

# ENV PYTHONPATH /usr/src/pythonpath

COPY schema.json .
COPY run-new.sh run.sh
COPY wait-for-it.sh .

RUN chmod +x run.sh
RUN chmod +x wait-for-it.sh